export const TOGGLE_PLAYER = 'TOGGLE_PLAYER';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_GLOBAL_SCORE = 'UPDATE_GLOBAL_SCORE';
export const UPDATE_DICE = 'UPDATE_DICE';
export const RESET_DICE = 'RESET_DICE';
export const RESET_ROUNDS = 'RESET_ROUNDS';
export const RESET_PLAYERS = 'RESET_PLAYERS';
export const ROLE_DICE = 'ROLE_DICE';
export const WINNER_PLAYER = 'WINNER_PLAYER';

